##########################################################################
# If not stated otherwise in this file or this component's LICENSE
# file the following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
CURRENTPATH = `pwd`
all: librdkatatspi2.so

VPATH=atspi2 tts screenreader

SEARCH=\
  -I. \
  -I./atspi2 \
  -I./tts \
  -I./screenreader \
  -I$(SYSROOT_INCLUDES_DIR) \
  -I$(SYSROOT_INCLUDES_DIR)/glib-2.0 \
  -I$(SYSROOT_LIBS_DIR)/glib-2.0/include

EXTRA_CXXFLAGS += -Wno-attributes -Wall -g -fpermissive $(SEARCH) -std=c++17 -fPIC
EXTRA_LDFLAGS = -lglib-2.0 -lTTSClient -Wl,-rpath=../../,-rpath=./ -Wl,-soname,librdkatatspi2.so.0

ifdef ENABLE_RDK_LOGGER
EXTRA_CXXFLAGS += -DUSE_RDK_LOGGER
EXTRA_LDFLAGS += -lrdkloggers -llog4c
endif

OBJDIR=obj
includes = $(wildcard ./*.h)

$(OBJDIR)/%.o : ./%.cpp ${includes}
	@[ -d $(OBJDIR) ] || mkdir -p $(OBJDIR)
	$(CXX) -c $(CXXFLAGS) $(EXTRA_CXXFLAGS) $< -o $@

rdkat_SRCS=rdkat-atspi2.cpp logger.cpp CAtspiAccessibleObject.cpp CAtspiRegistryService.cpp CDBusClientRegistry.cpp CScreenReader.cpp CFactory.cpp CTTSClientThunder.cpp
rdkat_OBJS=$(patsubst %.cpp, $(OBJDIR)/%.o, $(notdir $(rdkat_SRCS)))
rdkat_OBJS:=$(patsubst %.c, $(OBJDIR)/%.o, $(rdkat_OBJS))
rdkat_OBJS: $(rdkat_SRCS)
rdkat_OBJS_ALL=$(rdkat_OBJS)
librdkatatspi2.so: $(rdkat_OBJS_ALL)
	$(CXX) $(rdkat_OBJS_ALL) $(LDFLAGS) $(EXTRA_LDFLAGS) -shared -fPIC -o librdkatatspi2.so

install:
	@mkdir -p ${INSTALL_PATH}/usr/lib/
	@cp -f librdkatatspi2.so ${INSTALL_PATH}/usr/lib/librdkatatspi2.so.0.0
	@ln -sr ${INSTALL_PATH}/usr/lib/librdkatatspi2.so.0 ${INSTALL_PATH}/usr/lib/librdkatatspi2.so
	@ln -sr ${INSTALL_PATH}/usr/lib/librdkatatspi2.so.0.0 ${INSTALL_PATH}/usr/lib/librdkatatspi2.so.0
	
	@mkdir -p ${INSTALL_PATH}/usr/include/
	@cp -f rdkat-atspi2.h ${INSTALL_PATH}/usr/include

clean:
	@rm -rf obj/* librdkatatspi2.so*
